version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - app_network
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./etc/nginx/conf.d
        target: /etc/nginx/conf.d
      - type: bind
        source: ./homestead
        target: /var/www/html
    depends_on:
      - php70
      - php71
      - php74
      - php81
      - php83

  php70:
    build:
      context: ./docker/php/70
      dockerfile: Dockerfile
    container_name: php70
    networks:
      - app_network
    volumes:
      - type: bind
        source: ./homestead
        target: /var/www/html
  php71:
    build:
      context: ./docker/php/71
      dockerfile: Dockerfile
    container_name: php71
    networks:
      - app_network
    volumes:
      - type: bind
        source: ./homestead
        target: /var/www/html      
  
  php74:
    build:
      context: ./docker/php/74
      dockerfile: Dockerfile
    container_name: php74
    networks:
      - app_network
    volumes:
      - type: bind
        source: ./homestead
        target: /var/www/html
  php81:
    build:
      context: ./docker/php/81
      dockerfile: Dockerfile
    container_name: php81
    networks:
      - app_network
    volumes:
      - type: bind
        source: ./homestead
        target: /var/www/html
  php83:
    build:
      context: ./docker/php/83
      dockerfile: Dockerfile
    container_name: php83
    networks:
      - app_network
    volumes:
      - type: bind
        source: ./homestead
        target: /var/www/html

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    networks:
      - app_network
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - type: bind
        source: ./etc/mysql/conf.d/my.cnf
        target: /etc/mysql/conf.d/my.cnf
        read_only: true
    command: --sql_mode=""

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app_network
    volumes:
      - mongodb_data:/data/db
    

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
  mongodb_data:
